import { ArrowLeft } from 'lucide-react';

function Privacy() {
  return (
    <div className="min-h-screen bg-gray-50 pt-24 pb-20">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="mb-8">
          <a
            href="/"
            className="inline-flex items-center text-blue-600 hover:text-blue-700 transition-colors"
          >
            <ArrowLeft className="h-4 w-4 mr-2" />
            Back to Homepage
          </a>
        </div>

        <div className="bg-white p-8 rounded-xl shadow-md">
          <h1 className="text-3xl font-bold text-gray-900 mb-6">Privacy Policy</h1>

          <div className="prose prose-blue max-w-none">
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">1. Introduction</h2>
            <p className="text-gray-600 mb-4">
              SyncNext ("we," "our," or "us") respects your privacy and is committed to protecting it through our compliance with this policy. This Privacy Policy describes the types of information we may collect from you or that you may provide when you visit our website and our practices for collecting, using, maintaining, protecting, and disclosing that information.
            </p>

            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">2. Information We Collect</h2>
            <p className="text-gray-600 mb-4">
              We only collect information through Google Analytics to help us understand how visitors interact with our website. This may include:
            </p>
            <ul className="list-disc pl-6 mb-4 text-gray-600">
              <li>Usage details such as traffic data, location data, and other communication data.</li>
              <li>Information about your computer and internet connection, including your IP address, operating system, and browser type.</li>
              <li>Pages that you visit before and after navigating to our website.</li>
            </ul>
            <p className="text-gray-600 mb-4">
              All data collected through Google Analytics is anonymous and does not personally identify you.
            </p>

            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">3. How We Use Your Information</h2>
            <p className="text-gray-600 mb-4">
              We use the information collected through Google Analytics to:
            </p>
            <ul className="list-disc pl-6 mb-4 text-gray-600">
              <li>Understand and analyze the usage trends and preferences of our visitors.</li>
              <li>Improve our website and user experience.</li>
              <li>Develop new products, services, features, and functionality.</li>
            </ul>

            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">4. Cookies and Tracking Technologies</h2>
            <p className="text-gray-600 mb-4">
              Google Analytics uses cookies to collect information. A cookie is a small file placed on the hard drive of your computer. You may refuse to accept browser cookies by activating the appropriate setting on your browser. However, if you select this setting you may be unable to access certain parts of our website.
            </p>

            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">5. Third-Party Use of Cookies</h2>
            <p className="text-gray-600 mb-4">
              Google Analytics may use cookies to help us analyze how users use our site. The information generated by the cookie about your use of the website will be transmitted to and stored by Google on servers in the United States. Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators and providing other services relating to website activity and internet usage.
            </p>

            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">6. Data Security</h2>
            <p className="text-gray-600 mb-4">
              We have implemented measures designed to secure your information from accidental loss and from unauthorized access, use, alteration, and disclosure.
            </p>

            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">7. Changes to Our Privacy Policy</h2>
            <p className="text-gray-600 mb-4">
              We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
            </p>

            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">8. Contact Information</h2>
            <p className="text-gray-600 mb-4">
              If you have any questions or concerns about this Privacy Policy, please contact us.
            </p>
          </div>

          <div className="mt-8 pt-6 border-t border-gray-200">
            <p className="text-sm text-gray-500">
              Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Privacy;
